config/routes.rb
Kz::Application.routes.draw do
  resources :tender_states

  resources :customers

  resources :product_types

  resources :tenders do
    resources :lots do
      resources :productions
    end
  end

  get "home/index"

    resources :tender_types
    resources :measures

  root :to => 'home#index'

end

app/models/tender_state.rb
class TenderState < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/tender_states_controller.rb
class TenderStatesController < ApplicationController
  # GET /tender_states
  # GET /tender_states.json
  def index
    @tender_states = TenderState.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tender_states }
    end
  end

  # GET /tender_states/1
  # GET /tender_states/1.json
  def show
    @tender_state = TenderState.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tender_state }
    end
  end

  # GET /tender_states/new
  # GET /tender_states/new.json
  def new
    @tender_state = TenderState.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tender_state }
    end
  end

  # GET /tender_states/1/edit
  def edit
    @tender_state = TenderState.find(params[:id])
  end

  # POST /tender_states
  # POST /tender_states.json
  def create
    @tender_state = TenderState.new(params[:tender_state])

    respond_to do |format|
      if @tender_state.save
        format.html { redirect_to @tender_state, notice: 'Tender state was successfully created.' }
        format.json { render json: @tender_state, status: :created, location: @tender_state }
      else
        format.html { render action: "new" }
        format.json { render json: @tender_state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tender_states/1
  # PUT /tender_states/1.json
  def update
    @tender_state = TenderState.find(params[:id])

    respond_to do |format|
      if @tender_state.update_attributes(params[:tender_state])
        format.html { redirect_to @tender_state, notice: 'Tender state was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tender_state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tender_states/1
  # DELETE /tender_states/1.json
  def destroy
    @tender_state = TenderState.find(params[:id])
    @tender_state.destroy

    respond_to do |format|
      format.html { redirect_to tender_states_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tender_states_helper.rb
module TenderStatesHelper
end

app/views/tender_states/_form.html.erb
<%= form_for(@tender_state) do |f| %>
  <% if @tender_state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tender_state.errors.count, "error") %> prohibited this tender_state from being saved:</h2>

      <ul>
      <% @tender_state.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tender_states/edit.html.erb
<h1>Editing tender_state</h1>

<%= render 'form' %>

<%= link_to 'Show', @tender_state %> |
<%= link_to 'Back', tender_states_path %>

app/views/tender_states/index.html.erb
<h1>Listing tender_states</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tender_states.each do |tender_state| %>
  <tr>
    <td><%= tender_state.name %></td>
    <td><%= link_to 'Show', tender_state %></td>
    <td><%= link_to 'Edit', edit_tender_state_path(tender_state) %></td>
    <td><%= link_to 'Destroy', tender_state, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tender state', new_tender_state_path %>
<br/>
<%= link_to 'Home', root_path %>

app/views/tender_states/new.html.erb
<h1>New tender_state</h1>

<%= render 'form' %>

<%= link_to 'Back', tender_states_path %>

app/views/tender_states/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @tender_state.name %>
</p>


<%= link_to 'Edit', edit_tender_state_path(@tender_state) %> |
<%= link_to 'Back', tender_states_path %>