config/routes.rb
Kz::Application.routes.draw do
  resources :tender_states

  resources :customers

  resources :product_types

  resources :tenders do
    resources :lots do
      resources :productions
    end
  end

  get "home/index"

    resources :tender_types
    resources :measures

  root :to => 'home#index'

end

app/models/tender.rb
class Tender < ActiveRecord::Base

  attr_accessible :app_open_date, :app_open_place, :app_order, :app_place,
  :app_view_date, :app_view_place, :doc_begin_date, :doc_end_date,
  :doc_order,:doc_place, :end_app_date, :name, :placing_date,
  :registry_number,:start_app_date, :tender_type_id, :customer_id, :tender_state_id
  
  validates :name, :presence => true, :length => { :minimum => 5}
  validates :tender_state_id, :presence => true
  validates :tender_type_id, :presence => true
  validates :customer_id, :presence => true
  validate :validate_app_view_date_after_app_open_date

  has_many :lots
  belongs_to :tender_type
  belongs_to :customer
  belongs_to :tender_state


  def validate_app_view_date_after_app_open_date
    if app_view_date && app_open_date
      errors.add(:app_view_date,"Should be after App open date") if app_view_date < app_open_date
    end
  end

  def self.search(sname, sreg_num, scustomer, stender_type, stender_state, sprice_s,sprice_do, date_reg_s,date_reg_po,placing_date_s,placing_date_po)
    if (sname)
      if (sname!="")
        cond1 = "name LIKE ?"
        val1 = "%#{sname}%"
      end
      if (sreg_num!="")
        cond2 = "registry_number LIKE ?"
        val2 = "%#{sreg_num}%"
      end
      if (scustomer!="0")
        cond3 = "customer_id = ?"
        val3 = scustomer
      end
      if (stender_type!="0")
        cond4 = "tender_type_id = ?"
        val4 = stender_type
      end
      if (stender_state!="0")
        cond5 = "tender_state_id = ?"
        val5 = stender_state
      end
      if (sprice_s!="")
        cond6 = "price >= ?"
        val6 = sprice_s
      end
      if (sprice_do!="")
        cond7 = "price <= ?"
        val7 = sprice_do
      end
      if (date_reg_s!="")
        cond8 = "created_at >= ?"
        val8 = date_reg_s
      end
      if (date_reg_po!="")
        cond9 = "created_at <= ?"
        val9 = date_reg_po
      end
      if (placing_date_s!="")
        cond10 = "placing_date >= ?"
        val10 = placing_date_s
      end
      if (placing_date_po!="")
        cond11 = "placing_date <= ?"
        val11 = placing_date_po
      end
      cond = [cond1,cond2,cond3,cond4,cond5,cond6,cond7,cond8,cond9,cond10,cond11].compact.join(' AND ')
      cond_val = [cond,val1,val2,val3,val4,val5,val6,val7,val8,val9,val10,val11].compact
      find(:all, :conditions => cond_val)
    else
      find(:all)
      end
  end
end

app/models/tender_type.rb
class TenderType < ActiveRecord::Base
  attr_accessible :code, :name
end

app/controllers/tenders_controller.rb
class TendersController < ApplicationController
  # GET /tenders
  # GET /tenders.json
  def index
    start_default = Date.civil(2010,1,1)
    end_default  = Date.civil(2015,1,1)
    @date_reg_s=Date.civil(params[:sdate_reg_s][:year].to_i,params[:sdate_reg_s][:month].to_i,params[:sdate_reg_s][:day].to_i) rescue start_default
    @date_reg_po=Date.civil(params[:sdate_reg_po][:year].to_i,params[:sdate_reg_po][:month].to_i,params[:sdate_reg_po][:day].to_i) rescue end_default
    @placing_date_s=Date.civil(params[:splacing_date_s][:year].to_i,params[:splacing_date_s][:month].to_i,params[:splacing_date_s][:day].to_i) rescue start_default
    @placing_date_po=Date.civil(params[:splacing_date_po][:year].to_i,params[:splacing_date_po][:month].to_i,params[:splacing_date_po][:day].to_i) rescue end_default
    @tenders = Tender.search(params[:sname], params[:sreg_num], params[:scustomer], params[:stender_type],
    params[:stender_state],params[:sprice_s],params[:sprice_do],@date_reg_s,@date_reg_po,@placing_date_s,@placing_date_po)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tenders }
    end
  end

  # GET /tenders/1
  # GET /tenders/1.json
  def show
    @tender = Tender.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tender }
    end
  end

  # GET /tenders/new
  # GET /tenders/new.json
  def new
    @tender = Tender.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tender }
    end
  end

  # GET /tenders/1/edit
  def edit
    @tender = Tender.find(params[:id])
  end

  # POST /tenders
  # POST /tenders.json
  def create
    @tender = Tender.new(params[:tender])

    respond_to do |format|
      if @tender.save
        format.html { redirect_to @tender, notice: t(:Tender_created) }
        format.json { render json: @tender, status: :created, location: @tender }
      else
        format.html { render action: "new" }
        format.json { render json: @tender.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tenders/1
  # PUT /tenders/1.json
  def update
    @tender = Tender.find(params[:id])

    respond_to do |format|
      if @tender.update_attributes(params[:tender])
        format.html { redirect_to @tender, notice: t(:Tender_was_successfully_updated) }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tender.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tenders/1
  # DELETE /tenders/1.json
  def destroy
    @tender = Tender.find(params[:id])
    @tender.destroy

    respond_to do |format|
      format.html { redirect_to tenders_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/tenders_helper.rb
module TendersHelper
end

app/views/tenders/_form.html.erb
<%= form_for(@tender) do |f| %>
  <% if @tender.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(@tender.errors.count, "error") %> prohibited this tender from being saved:</h4>

      <ul>
      <% @tender.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <table>
      <tr>
        <td class="right"><b><%= f.label :registry_number %></b></td>
        <td><%= f.text_field :registry_number %></td>
      </tr>
      <tr>
        <td class="right"><b><%= f.label :name %></b></td>
        <td><%= f.text_field :name %></td>
      </tr>
      <tr>
        <td class="right"><b><%= f.label :placing_date %></b></td>
        <td><%= f.date_select :placing_date %></td>
      </tr>
      <tr>
        <td class="right"><b><%= f.label :tender_type_id %></b></td>
        <td><%= collection_select(:tender, :tender_type_id, TenderType.all, :id, :name) %></td>
      </tr>
      <tr>
        <td class="right"><b><%= f.label :tender_state_id %></b></td>
        <td><%= collection_select(:tender, :tender_state_id, TenderState.all, :id, :name) %></td>
      </tr>
      <tr>
        <td class="right"><b><%= f.label :customer_id %></b></td>
        <td><%= collection_select(:tender, :customer_id, Customer.all, :id, :name) %></td>
      </tr>
      <tr>
        <td class="right"><b><%= f.label :start_app_date %></b></td>
        <td><%= f.date_select :start_app_date %></td>
      </tr>
      <tr>
        <td class="right"><b><%= f.label :end_app_date %></b></td>
        <td><%= f.date_select :end_app_date %></td>
      </tr>
      <tr>
        <td class="right"><b><%= f.label :app_place %></b></td>
        <td><%= f.text_field :app_place %></td>
      </tr>
      <tr>
        <td class="right"><b><%= f.label :app_order %></b></td>
        <td><%= f.text_field :app_order %></td>
      </tr>
      <tr>
        <td class="right"><b><%= f.label :app_open_date %></b></td>
        <td><%= f.date_select :app_open_date %></td>
      </tr>
      <tr>
        <td class="right"><b><%= f.label :app_open_place %></b></td>
        <td> <%= f.text_field :app_open_place %></td>
      </tr>
      <tr>
        <td class="right"><b><%= f.label :app_view_date %></b></td>
        <td><%= f.date_select :app_view_date %></td>
      </tr>
      <tr>
        <td class="right"><b><%= f.label :app_view_place %></b></td>
        <td><%= f.text_field :app_view_place %></td>
      </tr>
      <tr>
        <td class="right"><b><%= f.label :doc_begin_date %></b></td>
        <td><%= f.date_select :doc_begin_date %></td>
      </tr>
      <tr>
        <td class="right"><b><%= f.label :doc_end_date %></b></td>
        <td><%= f.date_select :doc_end_date %></td>
      </tr>
      <tr>
        <td class="right"><b><%= f.label :doc_place %></b></td>
        <td><%= f.text_field :doc_place %></td>
      </tr>
      <tr>
        <td class="right"><b><%= f.label :doc_order %></b></td>
        <td><%= f.text_field :doc_order %></td>
      </tr>
      <tr>
        <td></td>
        <td><div class="actions"><%= f.submit action_name="Сохранить"%></div></td>
      </tr>
    </table>
<% end %>

app/views/tenders/edit.html.erb
<h2>Карточка торгов (правка)</h2>
<p class="operations"><%= link_to 'Реестр торгов', tenders_path %> <%= link_to 'Отмена', @tender %></p>

<%= render 'form' %>

app/views/tenders/index.html.erb
<h2>Реестр торгов</h2>
<p class="operations"><%= link_to 'Создать торги', new_tender_path %></p>
<fieldset>
  <%= form_tag tenders_path, :method => "get" do %>
    <table>
      <tr>
        <td class="search_title">Реестровый номер:</td>
        <td class="search_field"><%= text_field_tag :sreg_num, params[:sreg_num] %></td>
        <td class="search_title">Дата создания c</td>
        <td class="search_field"><%= select_date @date_reg_s, :prefix => :sdate_reg_s, :order => [:day, :month, :year]%>
           по <%= select_date @date_reg_po, :prefix => :sdate_reg_po, :order => [:day, :month, :year]%></td></tr>
      <tr>
        <td class="search_title">Наименование торгов:</td>
        <td class="search_field"><%= text_field_tag :sname, params[:sname] %></td>
        <td class="search_title">План. дата размещения c</td>
        <td class="search_field"><%= select_date @placing_date_s, :prefix => :splacing_date_s, :order => [:day, :month, :year]%>
          по <%= select_date @placing_date_po, :prefix => :splacing_date_po, :order => [:day, :month, :year]%></td>
      </tr>
      <tr>
        <td class="search_title">Наименование заказчика:</td>
        <td class="search_field"><%= select_tag :scustomer, options_from_collection_for_select(Customer.all, :id, :name, params[:scustomer]) %></td>
        <td class="search_title">Начальная цена от</td>
        <td class="search_field"><%= text_field_tag :sprice_s, params[:sprice_s] %> до <%= text_field_tag :sprice_do, params[:sprice_do] %></td>
      </tr>
      <tr>
        <td class="search_title">Способ закупки:</td>
        <td class="search_field"><%= select_tag :stender_type, options_from_collection_for_select(TenderType.all, :id, :name, params[:stender_type]) %></td>
        <td class="search_title">Статус:</td>
        <td class="search_field"><%= select_tag :stender_state, options_from_collection_for_select(TenderState.all, :id, :name, params[:stender_state]) %></td>
      </tr>
      <tr><td></td><td class="search_button"><%= submit_tag "Найти торги", :name => nil %> <%= link_to "Очистить", tenders_path%></td><td></td><td></td></tr>
    </table>
<% end %>
</fieldset>
<table>
  <tr>
    <th class="operations">Операции</th>
    <th class="reg_num">Реестровый номер торгов</th>
    <th>Наименование торгов</th>
    <th class="date">План. дата размещения</th>
    <th>Начальная цена</th>
    <th>Способ закупки</th>
    <th>Статус</th>
    <th>Заказчик</th>
    <th>Дата создания</th>
  </tr>

<% @tenders.each do |tender| %>
  <tr>
    <td><%= link_to 'Смотр', tender %>&nbsp;
      <%= link_to 'Ред', edit_tender_path(tender) %>&nbsp;
      <%= link_to 'Уд', tender, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <td class="number"><%= tender.registry_number %></td>
    <td><%= tender.name %></td>
    <td class="date"><%=l tender.placing_date %></td>
    <td class="number"><%= number_to_currency(tender.price) %></td>
    <td><%= tender.tender_type.name %></td>
    <td><%= tender.tender_state.name %></td>
    <td><%= tender.customer.name %></td>
    <td class="date"><%=l tender.created_at.to_date %></td>
  </tr>
<% end %>
</table>

<br />

app/views/tenders/new.html.erb
<h2>Новые торги</h2>
<p class="operations"><%= link_to 'Back', tenders_path %></p>
<%= render 'form' %>

app/views/tenders/show.html.erb
<h2>Карточка торгов</h2>
<% if notice %>
      <div class="flash_notice"><%= notice %></div>
<% end %>
<p class="operations"><%= link_to 'Реестр торгов', tenders_path %> <%= link_to 'Редактировать', edit_tender_path(@tender) %></p>
<%= form_for(@tender) do |f| %>
<table>
  <tr>
    <td class="right"><b><%= f.label :registry_number %></b></td>
    <td><%= @tender.registry_number %></td>
  </tr>
  <tr>
    <td class="right"><b><%= f.label :name %></b></td>
    <td><%= @tender.name %></td>
  </tr>
  <tr>
    <td class="right"><b><%= f.label :placing_date %></b></td>
    <td><%=l @tender.placing_date %></td>
  </tr>
  <tr>
    <td class="right"><b><%= f.label :price %></b></td>
    <td><%= number_to_currency(@tender.price) %></td>
  </tr>
  <tr>
    <td class="right"><b><%= f.label :tender_type_id %></b></td>
    <td><%= @tender.tender_type.name %></td>
  </tr>
  <tr>
    <td class="right"><b><%= f.label :tender_state_id %></b></td>
    <td><%= @tender.tender_state.name %></td>
  </tr>
  <tr>
    <td class="right"><b><%= f.label :customer_id %></b></td>
    <td><%= @tender.customer.name %></td>
  </tr>
  <tr>
    <td class="right"><b><%= f.label :created_at %></b></td>
    <td><%=l @tender.created_at.to_date %></td>
  </tr>
  <tr>
    <td class="right"><b><%= f.label :start_app_date %></b></td>
    <td><%=l @tender.start_app_date %></td>
  </tr>
  <tr>
    <td class="right"><b><%= f.label :end_app_date %></b></td>
    <td><%=l @tender.end_app_date %></td>
  </tr>
  <tr>
    <td class="right"><b><%= f.label :app_place %></b></td>
    <td><%= @tender.app_place %></td>
  </tr>
  <tr>
    <td class="right"><b><%= f.label :app_order %></b></td>
    <td><%= @tender.app_order %></td>
  </tr>
  <tr>
    <td class="right"><b><%= f.label :app_open_date %></b></td>
    <td><%=l @tender.app_open_date %></td>
  </tr>
  <tr>
    <td class="right"><b><%= f.label :app_open_place %></b></td>
    <td><%= @tender.app_open_place %></td>
  </tr>
  <tr>
    <td class="right"><b><%= f.label :app_view_date %></b></td>
    <td><%=l @tender.app_view_date %></td>
  </tr>
  <tr>
    <td class="right"><b><%= f.label :app_view_place %></b></td>
    <td><%= @tender.app_view_place %></td>
  </tr>
  <tr>
    <td class="right"><b><%= f.label :doc_begin_date %></b></td>
    <td><%=l @tender.doc_begin_date %></td>
  </tr>
  <tr>
    <td class="right"><b><%= f.label :doc_end_date %></b></td>
    <td><%=l @tender.doc_end_date %></td>
  </tr>
  <tr>
    <td class="right"><b><%= f.label :doc_place %></b></td>
    <td><%= @tender.doc_place %></td>
  </tr>
  <tr>
    <td class="right"><b><%= f.label :doc_order %></b></td>
    <td><%= @tender.doc_order %></td>
  </tr>
</table>
    <%end%>

<h3>Список лотов</h3>
<p class="operations"><%= link_to 'Создать лот', new_tender_lot_path(@tender) %></p>
<table>
  <tr>
    <th class="operations">Операции</th>
    <th>Наименование лота</th>
    <th>Начальная цена</th>
    <th>Срок предоставления договора</th>
  </tr>

  <% @tender.lots.each do |mylot| %>
      <tr>
        <td><%= link_to 'Смотр', tender_lot_path(@tender, mylot)%>&nbsp;
          <%= link_to 'Ред', edit_tender_lot_path(@tender, mylot)%>&nbsp;
          <%= link_to 'Уд', [@tender, mylot], method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= mylot.name %></td>
        <td class="number"><%= number_to_currency(mylot.start_price) %></td>
        <td><%=l mylot.contract_delivery_date %></td>
      </tr>
  <% end %>
</table>
<br/>