config/routes.rb
Kz::Application.routes.draw do
  resources :tender_states

  resources :customers

  resources :product_types

  resources :tenders do
    resources :lots do
      resources :productions
    end
  end

  get "home/index"

    resources :tender_types
    resources :measures

  root :to => 'home#index'

end

app/models/lot.rb
class Lot < ActiveRecord::Base
  validates :name, :presence => true, :length => { :minimum => 5}
  mount_uploader :contract, ContractUploader
  mount_uploader :tz_file, TzFileUploader
  mount_uploader :initial_price_reasoning_file, InitialPriceReasoningFileUploader
  mount_uploader :other_documents_file, OtherDocumentsFileUploader
  validates_numericality_of :application_pledge_sum
  validates_numericality_of :contract_pledge_sum
  validates :application_pledge_percent, :numericality => {
      :less_than_or_equal_to => 100,
      :greater_than_or_equal_to => 0
  }
  validates :contract_pledge_percent, :numericality => {
      :less_than_or_equal_to => 100,
      :greater_than_or_equal_to => 0
  }
  validates :start_price, :numericality => {:greater_than_or_equal_to => 1000}
  belongs_to :tender
  has_many :productions
  attr_accessible :contract_delivery_date, :name, :start_price, :contract, :contract_cache, :remove_contract,
                  :tz_file, :tz_file_cache, :remove_tz_file,
                  :initial_price_reasoning_file, :initial_price_reasoning_file_cache, :remove_initial_price_reasoning_file,
                  :other_documents_file, :other_documents_file_cache, :remove_other_documents_file,
                  :order_number, :initial_price_description, :participant_demands, :subcontractor_demands, :application_pledge,
                  :application_pledge_percent, :application_pledge_sum, :application_pledge_form, :contract_pledge, :contract_pledge_percent,
                  :contract_pledge_sum, :contract_pledge_form
  after_save :update_tender_sum
  after_destroy :update_tender_sum_destroy

  private
  def update_tender_sum
    return true unless start_price_changed?
    Tender.update_counters tender.id,
                           :price => (start_price - (start_price_was || 0))
    return true
  end

  def update_tender_sum_destroy
    Tender.update_counters tender.id,
                           :price => ( - start_price_was)
    return true
  end

end

app/controllers/lots_controller.rb
class LotsController < ApplicationController
	def create
    @tender = Tender.find(params[:tender_id])
    @lot = @tender.lots.create(params[:lot])
    if(@lot.valid?)
      redirect_to tender_lot_path(@lot.tender,@lot), notice: t(:Lot_was_successfully_created)
    else
      render action: "new"
    end
  end

  def show
    @tender = Tender.find(params[:tender_id])
    @lot = Lot.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @lot }
    end
  end

  def new
    @tender = Tender.find(params[:tender_id])
    @lot = @tender.lots.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @lot }
    end
  end

  def edit
    @lot = Lot.find(params[:id])
  end

  def update
    @lot = Lot.find(params[:id])

    respond_to do |format|
      if @lot.update_attributes(params[:lot])
        format.html { redirect_to tender_lot_path(@lot.tender,@lot), notice: t(:Lot_was_successfully_updated) }
        format.json { head :no_content }
      else
        format.html {
          #flash[:notice] = "qw"
          render action: "edit"
        }
        format.json { render json: @lot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tenders/1
  # DELETE /tenders/1.json
  def destroy
    @tender = Tender.find(params[:tender_id])
    @lot = Lot.find(params[:id])
    @lot.destroy

    respond_to do |format|
      format.html { redirect_to @tender }
      format.json { head :no_content }
    end
  end
end

app/helpers/lots_helper.rb
module LotsHelper
end

app/views/lots/_form.html.erb
<%= form_for([@lot.tender, @lot]) do |f| %>
    <table>
      <tr>
        <td class="right"><b><%= f.label :order_number %></b></td>
        <td><%= f.text_field :order_number %></td>
      </tr>
      <tr>
        <td class="right"><b><%= f.label :name %></b></td>
        <td><%= f.text_field :name %></td>
      </tr>
      <tr>
        <td class="right"><b><%= f.label :start_price%></b></td>
        <td><%= f.text_field :start_price%></td>
      </tr>
      <tr>
        <td class="right"><b><%= f.label :contract_delivery_date%></b></td>
        <td><%= f.date_select :contract_delivery_date, :start_year => 2013, :order => [:day, :month, :year]%></td>
      </tr>
      <tr>
        <td class="right"><b><%= f.label :contract%></b></td>
        <td> <%= f.file_field :contract %>
          <%= f.hidden_field :contract_cache %><br/>
          <%= @lot.contract.ident if @lot.contract? %>
          <label>
            <%= f.check_box :remove_contract %>
            <%= f.label :remove_contract %>
          </label></td>
      </tr>
      <tr>
        <td class="right"><b><%= f.label :tz_file%></b></td>
        <td> <%= f.file_field :tz_file %>
          <%= f.hidden_field :tz_file_cache %><br/>
          <%= @lot.tz_file.ident if @lot.tz_file? %>
          <label>
            <%= f.check_box :remove_tz_file %>
            <%= f.label :remove_tz_file %>
          </label></td>
      </tr>
      <tr>
        <td class="right"><b><%= f.label :initial_price_reasoning_file%></b></td>
        <td> <%= f.file_field :initial_price_reasoning_file %>
          <%= f.hidden_field :initial_price_reasoning_file_cache %><br/>
          <%= @lot.initial_price_reasoning_file.ident if @lot.initial_price_reasoning_file? %>
          <label>
            <%= f.check_box :remove_initial_price_reasoning_file %>
            <%= f.label :remove_initial_price_reasoning_file %>
          </label></td>
      </tr>
      <tr>
        <td class="right"><b><%= f.label :other_documents_file%></b></td>
        <td> <%= f.file_field :other_documents_file %>
          <%= f.hidden_field :other_documents_file_cache %><br/>
          <%= @lot.other_documents_file.ident if @lot.other_documents_file? %>
          <label>
            <%= f.check_box :remove_other_documents_file %>
            <%= f.label :remove_other_documents_file %>
          </label></td>
      </tr>
      <tr>
        <td class="right"><b><%= f.label :initial_price_description %></b></td>
        <td><%= f.text_field :initial_price_description %></td>
      </tr>
      <tr>
        <td class="right"><b><%= f.label :participant_demands %></b></td>
        <td><%= f.text_field :participant_demands %></td>
      </tr>
      <tr>
        <td class="right"><b><%= f.label :subcontractor_demands %></b></td>
        <td><%= f.text_field :subcontractor_demands %></td>
      </tr>
      <tr>
        <td class="right"><b><%= f.label :application_pledge %></b></td>
        <td><%= f.check_box :application_pledge %></td>
      </tr>
      <tr>
        <td class="right"><b><%= f.label :application_pledge_percent %></b></td>
        <td><%= f.text_field :application_pledge_percent %></td>
      </tr>
      <tr>
        <td class="right"><b><%= f.label :application_pledge_sum %></b></td>
        <td><%= f.text_field :application_pledge_sum %></td>
      </tr>
      <tr>
        <td class="right"><b><%= f.label :application_pledge_form %></b></td>
        <td><%= f.text_field :application_pledge_form %></td>
      </tr>
      <tr>
        <td class="right"><b><%= f.label :contract_pledge %></b></td>
        <td><%= f.check_box :contract_pledge %></td>
      </tr>
      <tr>
        <td class="right"><b><%= f.label :contract_pledge_percent %></b></td>
        <td><%= f.text_field :contract_pledge_percent %></td>
      </tr>
      <tr>
        <td class="right"><b><%= f.label :contract_pledge_sum %></b></td>
        <td><%= f.text_field :contract_pledge_sum %></td>
      </tr>
      <tr>
        <td class="right"><b><%= f.label :contract_pledge_form %></b></td>
        <td><%= f.text_field :contract_pledge_form %></td>
      </tr>
      <tr>
        <td></td>
        <td>  <div class="actions">
          <%= f.submit name="Сохранить"%>
        </div></td>
      </tr>
    </table>
<% end %>

app/views/lots/_lot.html.erb
  <table>
    <tr>
      <th>Операции</th>
      <th>Название лота</th>
      <th>Начальная цена</th>
      <th>Срок предоставления договора</th>
    </tr>
    <tr>
      <td>Show Edit Destroy</td>
      <td><%= lot.name %></td>
      <td><%= lot.start_price %></td>
      <td><%= lot.contract_delivery_date %></td>
    </tr>
  </table>

app/views/lots/edit.html.erb
<h2>Лот торгов (правка)</h2>
<p>Наименование торгов: <%= @lot.tender.name %>
</p>
<% if @lot.errors.any? %>
    <div id="error_explanation">
      <h3>Следующие ошибки (<%= pluralize(@lot.errors.count, "шт.")%>) не дают сохранить лот:</h3>
      <ul>
        <% @lot.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>
<p class="operations"><%= link_to 'Реестр торгов', tenders_path %>
  <%= link_to 'Карточка торгов', tender_path(@lot.tender) %>
  <%= link_to 'Отмена', tender_lot_path(@lot.tender, @lot) %></p>

<%= render 'form' %>

app/views/lots/new.html.erb
<h2>Новый лот</h2>
<% if @lot.errors.any? %>
    <div id="error_explanation">
      <h3>Следующие ошибки (<%= pluralize(@lot.errors.count, "шт.")%>) не дают сохранить лот:</h3>
      <ul>
        <% @lot.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>
<p class="operations"><%= link_to 'Back', @tender %></p>
<%= render 'form' %>

app/views/lots/show.html.erb
<h2>Лот торгов</h2>
<p>Наименование торгов: <%= @lot.tender.name %></p>
<% if notice %>
    <div class="flash_notice"><%= notice %></div>
<% end %>
<p class="operations"><%= link_to 'Реестр торгов', tenders_path %>
  <%= link_to 'Карточка торгов', tender_path(@lot.tender) %>
  <%= link_to 'Редактировать', edit_tender_lot_path(@lot.tender,@lot) %></p>
<%= form_for([@lot.tender,@lot]) do |f| %>
<table>
  <tr>
    <td class="right"><b><%= f.label :order_number %></b></td>
    <td><%= @lot.order_number %></td>
  </tr>
  <tr>
    <td class="right"><b><%= f.label :name %></b></td>
    <td><%= @lot.name %></td>
  </tr>
  <tr>
    <td class="right"><b><%= f.label :start_price %></b></td>
    <td><%= number_to_currency(@lot.start_price) %></td>
  </tr>
  <tr>
    <td class="right"><b><%= f.label :contract_delivery_date %></b></td>
    <td><%=l @lot.contract_delivery_date %></td>
  </tr>
  <tr>
    <td class="right"><b><%= f.label :contract %></b></td>
    <td>  <% if (@lot.contract?) %>
          <%= link_to(@lot.contract.ident, @lot.contract.url)%>
      <% end %></td>
  </tr>
  <tr>
    <td class="right"><b><%= f.label :tz_file %></b></td>
    <td>  <% if (@lot.tz_file?) %>
          <%= link_to(@lot.tz_file.ident, @lot.tz_file.url)%>
      <% end %></td>
  </tr>
  <tr>
    <td class="right"><b><%= f.label :initial_price_reasoning_file %></b></td>
    <td>  <% if (@lot.initial_price_reasoning_file?) %>
          <%= link_to(@lot.initial_price_reasoning_file.ident, @lot.initial_price_reasoning_file.url)%>
      <% end %></td>
  </tr>
  <tr>
    <td class="right"><b><%= f.label :other_documents_file %></b></td>
    <td>  <% if (@lot.other_documents_file?) %>
          <%= link_to(@lot.other_documents_file.ident, @lot.other_documents_file.url)%>
      <% end %></td>
  </tr>
  <tr>
    <td class="right"><b><%= f.label :initial_price_description %></b></td>
    <td><%= @lot.initial_price_description %></td>
  </tr>
  <tr>
    <td class="right"><b><%= f.label :participant_demands %></b></td>
    <td><%= @lot.participant_demands %></td>
  </tr>
  <tr>
    <td class="right"><b><%= f.label :subcontractor_demands %></b></td>
    <td><%= @lot.subcontractor_demands %></td>
  </tr>
  <tr>
    <td class="right"><b><%= f.label :application_pledge %></b></td>
    <td><%= t @lot.application_pledge?.yesno %></td>
  </tr>
  <tr>
    <td class="right"><b><%= f.label :application_pledge_percent %></b></td>
    <td><%= @lot.application_pledge_percent %></td>
  </tr>
  <tr>
    <td class="right"><b><%= f.label :application_pledge_sum %></b></td>
    <td><%= number_to_currency(@lot.application_pledge_sum) %></td>
  </tr>
  <tr>
    <td class="right"><b><%= f.label :application_pledge_form %></b></td>
    <td><%= @lot.application_pledge_form %></td>
  </tr>
  <tr>
    <td class="right"><b><%= f.label :contract_pledge %></b></td>
    <td><%=t @lot.contract_pledge?.yesno %></td>
  </tr>
  <tr>
    <td class="right"><b><%= f.label :contract_pledge_percent %></b></td>
    <td><%= @lot.contract_pledge_percent %></td>
  </tr>
  <tr>
    <td class="right"><b><%= f.label :contract_pledge_sum %></b></td>
    <td><%= number_to_currency(@lot.contract_pledge_sum) %></td>
  </tr>
  <tr>
    <td class="right"><b><%= f.label :contract_pledge_form %></b></td>
    <td><%= @lot.contract_pledge_form %></td>
  </tr>
</table>
  <% end %>
<h3>Список продукции</h3>
<p class="operations"><%= link_to 'Создать продукцию', new_tender_lot_production_path(@tender, @lot) %></p>
<table>
  <tr>
    <th class="operations">Операции</th>
    <th>№</th>
    <th>Код ОКДП</th>
    <th>Наименование продукции</th>
    <th>Закупается в электронной форме</th>
    <th>Количество</th>
    <th>Ед. изм.</th>
    <th>Цена</th>
  </tr>

  <% @lot.productions.each do |myprod| %>
      <tr>
        <td><%= link_to 'Смотр', tender_lot_production_path(@tender, @lot, myprod)%>&nbsp;
          <%= link_to 'Ред', edit_tender_lot_production_path(@tender, @lot, myprod)%>&nbsp;
          <%= link_to 'Уд', [@tender,@lot, myprod], method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= myprod.order_number %></td>
        <td><%= myprod.product_type.code %></td>
        <td><%= myprod.product_type.name %></td>
        <td><%= myprod.is_electronic.yesno %></td>
        <td><%= myprod.quantity %></td>
        <td><%= myprod.measure.name %></td>
        <td class="number"><%= number_to_currency(myprod.price) %></td>
      </tr>
  <% end %>
</table>